#!/usr/bin/env bash

BRANCH="main"
git checkout "$BRANCH"

for DAY in $(seq -w 02 30); do
    DATE="2024-06-$DAY 12:00:00"

    echo "Commit for $DATE" >> june-commits.log

    git add june-commits.log

    GIT_AUTHOR_DATE="$DATE" \
    GIT_COMMITTER_DATE="$DATE" \
    git commit -m "Daily commit for $DATE"
done

git push origin "$BRANCH"
